#
# Define ALL deploy hosts grouped by app.
#
# NOTE you CANNOT define same hosts for multiple app or ansible will read vars incorrectly.
#

all:
  children:
    itranswarp:
      hosts:
        # domain or ip list:
        1.domain.com:
        2.domain.com:
        10.0.1.100:
        10.0.1.101:
